apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  selector:
    matchLabels:
      type: local
  resources:
    requests:
      storage: 5Gi  
  accessModes:
    - ReadWriteOnce
  storageClassName: manual