apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-hpa
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60